name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['23', '24', '25', 'latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Python version
        run: python --version

      - name: Run unit tests
        run: ./install.py --test-only --verbose
        if: ${{ !startsWith(runner.os, 'macos') }}

      - name: Install WASI SDK
        id: wasi-sdk
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Check output variables
        shell: bash
        run:
          |
          echo "wasi-sdk-path: ${{ steps.wasi-sdk.outputs.wasi-sdk-path }}"
          echo "wasi-sdk-version: ${{ steps.wasi-sdk.outputs.wasi-sdk-version }}"
          echo "clang-path: ${{ steps.wasi-sdk.outputs.clang-path }}"
          echo "sysroot-path: ${{ steps.wasi-sdk.outputs.sysroot-path }}"

      # This should print a wasi-sdk version because `add-to-path` is true by default.
      - name: Check Clang version
        run: clang --version

      # These should be set because `add-to-path` is true by default.
      - name: Check environment variables
        shell: bash
        run: |
          echo "WASI_SDK_PATH: $WASI_SDK_PATH"
          echo "CC: $CC"
          echo "CXX: $CXX"

      - name: Create test C program
        shell: bash
        run:
          |
          cat > hello.c << 'EOF'
          #include <stdio.h>

          int main() {
              printf("Hello, WebAssembly!\n");
              return 0;
          }
          EOF

      - name: Build WebAssembly module
        shell: bash
        run:
          |
          clang hello.c -o hello.wasm
          ls -la hello.wasm
          file hello.wasm

      - name: Install Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1.1.0

      - name: Test WebAssembly module
        run: wasmtime hello.wasm

  test-cmake:
    name: Test CMake Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install WASI SDK
        uses: ./
        with:
          version: '25'

      - name: Create CMake project
        run:
          |
          mkdir cmake-test
          cd cmake-test

          cat > CMakeLists.txt << 'EOF'
          cmake_minimum_required(VERSION 3.16)
          project(HelloWasm C)

          add_executable(hello hello.c)
          EOF

          cat > hello.c << 'EOF'
          #include <stdio.h>

          int main() {
              printf("Hello from CMake + WASI!\n");
              return 0;
          }
          EOF

      - name: Build with CMake
        run:
          |
          cd cmake-test
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=$WASI_SDK_PATH/share/cmake/wasi-sdk.cmake
          cmake --build build
          ls -la build/hello
